### PR TITLE
Add David to design section

### PR DESCRIPTION
**Pull request by blakeprudhomme**

### CODE REVIEW

**Comment by kaspth** [comment]
@blakeprudhomme think you opened this PR against the main repo instead of your company's fork — and now you caught it, all good! Hope the handbook is helpful 😄

**Comment by blakeprudhomme** [comment]
Yep sorry. Thanks

**Comment by blakeprudhomme** [comment]
Yep sorry for the mistake. 🤦

We love Basecamp's handbook and workflow and have largely adopted it as our own! Appreciate it being open-sourced!

**Comment by kaspth** [comment]
No worries!

Awesome, glad to hear it, and yes, that's exactly why it's open source ❤️

**Pull request closed without merging**
